services:
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - 8080:80
    networks:
      - bridge-network
    extra_hosts:
      host.docker.internal: host-gateway
    tty: true

networks:
  bridge-network:
    driver: bridge
